branch-defaults:
  deploy/first-aws:
    environment: hello-world-env
  feat/express:
    environment: hello-world-env
    group_suffix: null
global:
  application_name: hello-world
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
